### PR TITLE
Integration tests

### LINKED ISSUE #326: Add integration tests
I saw green and happiness in https://github.com/matrix-org/go-neb/pull/322 but in reality it was very badly broken. Whilst we do have tests for services, we don't have testing around the bot framework itself. We should really add this to prevent humans making mistakes.

Specifically, a fake homeserver for Go-NEB to send `/sync` requests to as well as configuring via the HTTP API e.g `/configureClient` should do it. We're not interested in testing any specific service, so just the echo service will do.

### PR DESCRIPTION
**Pull request by nikofil**
* Add integration tests for neb joining an unencrypted / encrypted room and sending a message

(closes #326)

### CODE REVIEW

File: goneb_services_test.go [hunk 1]
```diff
@@ -54,3 +57,310 @@ func TestConfigureClient(t *testing.T) {
...
+						"sender_key":"%s",
+						"ciphertext":"%s",
+						"session_id":"%s"
+					},
+					"origin_server_ts": 10000,
+					"unsigned": {"age": 100},
+					"event_id": "evt125"
+				}]}}}
+		}
+	}`, identityKeyMock, string(ciphertext), ogsMock.ID())
```
Comment (Kegsay) [inline goneb_services_test.go:357]: Careful doing this as a JSON string, are we sure these 3 values only ever contain alphanumerics (no newlines or special chars?)

File: goneb_services_test.go [hunk 2]
```diff
@@ -54,3 +57,310 @@ func TestConfigureClient(t *testing.T) {
...
+		"Type": "echo",
+		"Id": "test_echo_service",
+		"UserID": "@link:hyrule",
+		"Config": {}
+	}`))
+	mux.ServeHTTP(mockWriter, serviceConfigReq)
+
+	// get the initial syncs out of the way
+	reqChan <- `{"next_batch":"11_22_33_44", "rooms": {}}`
+	reqChan <- `{"next_batch":"11_22_33_44", "rooms": {}}`
```
Comment (Kegsay) [inline goneb_services_test.go:124]: It's unclear why you do this twice. Perhaps a `reqChan` per user (echo service and main bot I guess is why this is twice?).

**Comment by nikofil** [comment]
Travis did run it: https://travis-ci.org/github/matrix-org/go-neb/builds/704347926
For some reason the link to Travis stops showing on Github after a while?

File: goneb_services_test.go (hunk 2 above)
Comment (nikofil) [reply goneb_services_test.go:124]: I believe first one is because of https://github.com/matrix-org/go-neb/blob/1be6c8c1cd445b9d1bbfcf955afc15b6c4da4c27/clients/bot_client.go#L124 which is done to get the state for all rooms which might be missing otherwise.
Second one is due to https://github.com/tulir/mautrix-go/blob/a45738638b0d43b9f1e7284dabeae26a117fb1e3/sync.go#L255 : when we're actually in the sync loop syncs without a `since` are ignored. As the first sync above does not set the syncer's `next_batch` var (as it's done outside the syncer's loop) we need a second one that will set the `next_batch` so that the next ones will be processed.

File: goneb_services_test.go (hunk 1 above)
Comment (nikofil) [reply goneb_services_test.go:357]: Yes, they're all base64.

File: goneb_services_test.go (hunk 2 above)
Comment (Kegsay) [reply goneb_services_test.go:124]: That's pretty fragile then. Perhaps it would be better to automatically send back an empty sync response if `since` is missing in the request? Then you wouldn't need this at all.

Comment (nikofil) [reply goneb_services_test.go]: True, that cleans up things a bit. I also moved the common test prologue which was setting up the mock server to a new func in a new commit.

**Comment by Kegsay** [comment]
Please don't force push all the time as it makes it hard to see the diff from before.
